[package]
name = "get-ipv6-with-pd-wrt"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
codegen-units = 1
strip = true
