[package]
name = "ipv6-addr-merge"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
argh = "0.1.13"
serde_json = "1.0.140"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
codegen-units = 1
strip = true
