# Origin config by @Kilerd

name: Build Canary Version

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  release:
    name: Release on ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ linux-x86_64, linux-arm64, ]
        include:
          - platform: linux-x86_64
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            bin: get-ipv6-with-pd-wrt
            
          - platform: linux-arm64
            target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            bin: get-ipv6-with-pd-wrt

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fix revision count

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        env:
          RUSTFLAGS: "-Zlocation-detail=none"
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          args: "--locked --release --bin get-ipv6-with-pd-wrt"
          use-rust-cache: false

      - name: Prepare assets
        shell: bash
        run: |
          tar -cvzf ${{ matrix.target }}.tar.gz LICENSE target/${{ matrix.target }}/release/${{ matrix.bin }}
          
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          rev_count=$(git rev-list --count HEAD)
          echo rev_count=${rev_count} >> $GITHUB_OUTPUT

      - name: Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.target }}.tar.gz
          tag_name: r${{ steps.vars.outputs.rev_count }}
          prerelease: false
          make_latest: true
